[phases.setup]
nixPkgs = ["python3", "ffmpeg", "gcc"]

[phases.install]
# CAMBIO CLAVE AQU√ç: Usamos 'python3 -m pip' en vez de solo 'pip'
cmds = ["python3 -m pip install -r requirements.txt"]

[start]
cmd = "gunicorn server:app"
