[phases.setup]
# AQUÍ ESTÁ EL CAMBIO: Agregamos "python3Packages.pip" explícitamente
nixPkgs = ["python3", "python3Packages.pip", "ffmpeg", "gcc"]

[phases.install]
# Ahora sí, invocamos a pip a través de python3
cmds = ["python3 -m pip install -r requirements.txt"]

[start]
cmd = "gunicorn server:app"
